# `dict`, `pandas.DataFrame` and `polars.DataFrame` in Different Geometries

In [1]:
import numpy as np
import pandas as pd
import polars as pl

from lets_plot import *
from lets_plot.bistro import *

In [2]:
LetsPlot.setup_html()

In [3]:
np.random.seed(42)
n = 25
data = {
    'u': np.random.uniform(-1, 1, size=n),
    'v': np.random.normal(size=n),
    'g': np.random.choice(["A", "B", "C"], size=n),
}

In [4]:
pd_df = pd.DataFrame(data)
print(pd_df.shape)
pd_df.head()

(25, 3)

          u         v  g
0 -0.250920 -0.629475  B
1  0.901429  0.597720  A
2  0.463988  2.559488  A
3  0.197317  0.394233  A
4 -0.687963  0.122219  A

In [5]:
pl_df = pl.DataFrame(data)
print(pl_df.shape)
pl_df.head()

(25, 3)

shape: (5, 3)
┌───────────┬───────────┬─────┐
│ u         ┆ v         ┆ g   │
│ ---       ┆ ---       ┆ --- │
│ f64       ┆ f64       ┆ str │
╞═══════════╪═══════════╪═════╡
│ -0.25092  ┆ -0.629475 ┆ B   │
│ 0.901429  ┆ 0.59772   ┆ A   │
│ 0.463988  ┆ 2.559488  ┆ A   │
│ 0.197317  ┆ 0.394233  ┆ A   │
│ -0.687963 ┆ 0.122219  ┆ A   │
└───────────┴───────────┴─────┘

In [6]:
def plot_comparison(title, get_plot):
    return gggrid([
        get_plot(data) + ggtitle(title, "Dictionary"),
        get_plot(pd_df) + ggtitle(title, "Pandas"),
        get_plot(pl_df) + ggtitle(title, "Polars"),
    ])

In [7]:
plot_comparison("ggplot()", lambda df: ggplot(df, aes("u", "v")) + geom_point())

In [8]:
plot_comparison("layer()", lambda df: ggplot() + layer(geom="point", mapping=aes("u", "v"), data=df))

In [9]:
plot_comparison("geom_point()", lambda df: ggplot() + geom_point(aes("u", "v"), data=df))

In [10]:
plot_comparison("geom_function()", lambda df: ggplot() + geom_function(aes(x="u"), data=df, fun=lambda t: t))

In [11]:
plot_comparison("stat_summary()", lambda df: ggplot(df, aes("g", "v")) + stat_summary())

In [12]:
plot_comparison("stat_summary_bin()", lambda df: ggplot(df, aes("u", "v")) + stat_summary_bin())

In [13]:
def get_corr_plot(data):
    if isinstance(data, dict):
        corr_data = {k: v for k, v in data.items() if k in ["u", "v"]}
    else:
        corr_data = data[["u", "v"]]
    return corr_plot(corr_data).tiles().build()
plot_comparison("corr_plot()", get_corr_plot)

In [14]:
plot_comparison("residual_plot()", lambda df: residual_plot(df, x="u", y="v"))

In [15]:
plot_comparison("qq_plot()", lambda df: qq_plot(df, sample="u"))

In [16]:
plot_comparison("joint_plot()", lambda df: joint_plot(df, x="u", y="v"))